<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="needle_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find needle_simulation)/urdf/common_properties.xacro"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="joint_range" value="2.35619"/>
  <xacro:property name="mass" value="0.25" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.05" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="1" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.5" /> <!-- Link 3 -->
  <xacro:property name="needle_radius" value="0.01" /> <!-- Link 3 -->
  <xacro:property name="needle_length" value="0.3" /> <!-- Link 3 -->
  <xacro:property name="needle_mass" value="0.001" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/needle_bot</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="base_link">
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="2 2 0.01"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="2 2 0.01"/>
      </geometry>
      <material name="orange"/>
    </visual> -->
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass*1000}"/>
      <inertia
	    ixx="${mass*1000 / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	    iyy="${mass*1000 / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	    izz="${mass*1000 / 12.0 * (width*width + width*width)}"/>
      </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <limit effort="30" velocity="1.57079633" lower="-${joint_range}" upper="${joint_range}" />
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
      	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
    	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	    ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	    iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	    izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <limit effort="30" velocity="1.57079633" lower="-${joint_range}" upper="${joint_range}" />
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
      	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass/2}"/>
      <inertia
	      ixx="${mass/2 / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	      iyy="${mass/2 / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	      izz="${mass/2 / 12.0 * (width*width + width*width)}"/>
      </inertial>
  </link>

  <!-- Needle Link -->
  <link name="needle_link">
    <collision>
      <origin xyz="0 ${needle_length/2} ${height3 - axel_offset}" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="${needle_length}" radius="${needle_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${needle_length/2} ${height3 - axel_offset}" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="${needle_length}" radius="${needle_radius}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${needle_length/2} 0" rpy="0 0 0"/>
      <mass value="${needle_mass}"/>
      <inertia
	      ixx="${needle_mass / 12.0 * ((2*needle_radius)*(2*needle_radius) + needle_length*needle_length)}" ixy="0.0" ixz="0.0"
	      iyy="${needle_mass / 12.0 * ((2*needle_radius)*(2*needle_radius) + needle_length*needle_length)}" iyz="0.0"
	      izz="${needle_mass / 12.0 * ((2*needle_radius)*(2*needle_radius) + needle_length*needle_length)}"/>
      </inertial>
  </link>

  <joint name="needle_joint" type="fixed">
    <parent link="link3"/>
    <child link="needle_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>